<?php

/**
 * @file
 * Contains ajax_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ajax_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ajax_example module.
    case 'help.page.ajax_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('illustrating ajax example') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ajax_example_theme() {
  return [
    'ajax_example' => [
      'render element' => 'children',
    ],
  ];
}
